name: CI for Pull-Request on dev

on:
  pull_request:
    branches: [ dev ]

env:
  GITHUB_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}

jobs:
  pr-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(major|minor|patch)\/(feature|hotfix)\/(UBI)-([0-9]{3})-([A-Za-z-]+)$' # e.g. "major|minor|patch/{{branch name}}"
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the branch name
          max_length: 60 # Max length of the branch name
          github_token: ${{ env.GITHUB_TOKEN }}
