name: CI for Merge on master/main

on:
  push:
    tags:
      - v*
    branches: [ master, main ]

env:
  MAIN_GKE_USER: ${{ secrets.SERVICEACCOUNT_EMAIL }}
  MAIN_GKE_JSON: ${{ secrets.SERVICEACCOUNT_JSONKEY }}

jobs:
  deploy-tooling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup helm/kubectl env
      run: |
        chmod 700 .github/tools_install.sh
        ./.github/tools_install.sh
        printf '${{ env.MAIN_GKE_JSON }}' > ubivius-deployments-5e62532eb5a9.json
        gcloud auth activate-service-account ${{ env.MAIN_GKE_USER }} --key-file=ubivius-deployments-5e62532eb5a9.json
        gcloud container clusters get-credentials prod-environment --zone us-east1-c --project ubivius-deployments
        
    - name: Push with valuefile
      run: |
        IN=$(echo ${GITHUB_REPOSITORY})
        NAME=${IN#"Ubivius/telemetry-"}
        chmod 700 .github/helm_update.sh
        ./.github/helm_update.sh $NAME

