name: CI to distribute workflows changes to master/main branches of telemetry projects

on:
  push:
    tags:
      - v*
    branches: [ master, main ]

env:
  GIT_USER: ${{ secrets.GIT_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
  GH_TOKEN: ${{ secrets.GITHUBCLI_TOKEN }}

jobs:
  pull-workflows-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: |
        export GH_TOKEN=${{ env.GH_TOKEN }}
        git config --global user.name "${{ env.GIT_USER }}"
        git config --global user.email "${{ env.GIT_EMAIL }}"
        mkdir ~/.ssh
        echo -e "${{ env.GIT_SSH_KEY }}" | tee ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        chmod 777 scripts/git_setup.sh
        ./scripts/git_setup.sh

    - name: Pull telemetry repositories and create new branches
      run: |
        chmod 777 scripts/prepare_main_telemetry.sh
        cat repository_list.txt | ./scripts/prepare_main_telemetry.sh

    - name: Update files and commit changes
      run: |
        chmod 777 scripts/add_files.sh
        cat repository_list.txt | ./scripts/add_files.sh

    - name: Create pull requests
      run: |
        chmod 777 scripts/create_main_pr.sh
        cat repository_list.txt | ./scripts/create_main_pr.sh
