name: CI to distribute workflows changes to dev branches of telemetry projects

on:
  push:
    tags:
      - v*
    branches: [ dev, feature/UBI-250-distribute-workflows-to-telemetry-projects ]

env:
  GIT_USER: ${{ secrets.GIT_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
  GH_TOKEN: ${{ secrets.GITHUBCLI_TOKEN }}

jobs:
  pull-workflows-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: |
        export GH_TOKEN=${{ env.GH_TOKEN }}; \
        git config --global user.name "${{ env.GIT_USER }}"; \
        git config --global user.email "${{ env.GIT_EMAIL }}"; \
        chmod 777 scripts/git_setup.sh
        ./scripts/git_setup.sh

    - name: Pull telemetry repositories and create new branches
      run: |
        cat repository_list.txt | \
        while read line; \
        do \
        git clone git@github.com/Ubivius/$line.git; \
        cd $line; \
        git checkout dev; \
        git checkout -b hotfix/workflows-update; \
        git add .; \
        git commit -m "Creating workflows update branch"; \
        git push --set-upstream origin hotfix/workflows-update; \
        cd ..; \
        done

    - name: Update files and commit changes
      run: |
        ls -la; \
        cat repository_list.txt | \
        while read line; \
        do \
        cd $line; \
        echo "Test"
        cd ..; \
        done

    - name: Create pull requests
      run: |
        cat repository_list.txt | \
        while read line; \
        do \
        cd $line; \
        ls -l; \
        cd ..; \
        done
